### ISSUE TITLE
Not blocking suggested posts

### ISSUE THREAD

**Issue by karigithub2000** [mrinc/F-B-Hide-Recommendations-and-Reels#110]
When Facebook first opens the add-on works, and as I scroll through the first few posts I can see it blocking posts from the feed. However, after Facebook loads the second batch of posts it stops blocking unwanted content. Also, if I have the "Hide all Blocks" setting turned off the elements that are blocked are not reduced in size like they were previously, so I still have to scroll through them.

![Screenshot 2023-12-25 210148](https://github.com/mrinc/F-B-Hide-Recommendations-and-Reels/assets/134016424/4d9079e9-4bc7-4913-9a44-40117164946d)
![Screenshot 2023-12-25 210500](https://github.com/mrinc/F-B-Hide-Recommendations-and-Reels/assets/134016424/78269290-dfcd-434e-ac52-afc82da6e6ab)
![Screenshot 2023-12-25 210809](https://github.com/mrinc/F-B-Hide-Recommendations-and-Reels/assets/134016424/4395bbe2-caac-405a-a46f-c6b784b48403)

**Comment by mrinc** [comment]
Hey,

If you see that again, please could you inspect element on the `Follow` link and send it's html here?  

I have not seen it yet from my side, so it's new, and will have to add it.

**Comment by karigithub2000** [comment]
> Hey,
> 
> If you see that again, please could you inspect element on the `Follow` link and send it's html here?
> 
> I have not seen it yet from my side, so it's new, and will have to add it.

Yup!

Here is the HTML for the follow button:
<span class="x193iq5w xeuugli x13faqbe x1vvkbs x1xmvt09 x6prxxf xvq8zen x1s688f x1fey0fg">Follow</span>

And here is the HTML on a join button that shows on similar posts:
<span class="x193iq5w xeuugli x13faqbe x1vvkbs x1xmvt09 x6prxxf xvq8zen x1s688f x1fey0fg">Join</span>

**Comment by mrinc** [comment]
Next version will have a match on `>Follow<` and `>Join<`  and that should sort this out - thanks!
