### ISSUE TITLE
The suggested for you still appears in the newsfeed

### ISSUE THREAD

**Issue by satch59** [mrinc/F-B-Hide-Recommendations-and-Reels#71]
The "suggested for you" still are visible. My browser is set to Polish. The default settings of the extension are applied.

**Comment by mrinc** [comment]
@satch59 - What lang is your facebook set too?  Is it also Polish?  
If so, is the 'suggested for you' showing as `Proponowana dla Ciebie` or something else?

**Comment by mrinc** [comment]
Ref: https://github.com/mrinc/F-B-Hide-Recommendations-and-Reels/blob/master/src/lib/langs.ts#L305C17-L305C39
