### ISSUE TITLE
"Suggested for you" section still appears

### ISSUE THREAD

**Issue by memecode** [mrinc/F-B-Hide-Recommendations-and-Reels#77]
I've configured the plugin to hide "Suggested for you" sections yet they still appear in my feed.

In fact that's all that's in my feed. The first 10 things are all just "Suggested for you".

**Comment by mrinc** [comment]
What Language do you have set on facebook?

**Comment by memecode** [comment]
Just plain old English.

**Comment by mrinc** [comment]
Please could you go into developer tools and copy-pasta the CC Cleaner logs for me?

**Comment by DLu** [comment]
I am having this problem too. I am not a stranger to the Firefox Dev tools, but am sure where to get the CC Cleaner logs.

**Comment by mrinc** [comment]
@memecode @DLu Just go into dev tools and look at the console... should all be there :)
