### ISSUE TITLE
Plan to hide Sponsored posts?

### ISSUE THREAD

**Issue by RussellBishop** [mrinc/F-B-Hide-Recommendations-and-Reels#81]
Are you planning to also hide Sponsored, or do you worry that'd be a lawsuit?

Loving this so far.

**Comment by mrinc** [comment]
If you press on the menu of the advert, it should hide it :)  
Unfortunately they make it EXTREMELY difficult to hide/identify these so we don't focus on them... it would be a whackamole to find and hide them.
