### ISSUE TITLE
Add support for Firefox Android

### ISSUE THREAD

**Issue by fabiogrum** [mrinc/F-B-Hide-Recommendations-and-Reels#90]
Tested version from Play Store: Firefox Beta 119.0b8

It seems that this extension doesn't work with Firefox on Android.
The extension works fine with the Firefox Desktop app on my PC.

More particularly, I installed the extension with this workaround: https://www.androidpolice.com/install-add-on-extension-mozilla-firefox-android/

This should help to filter out the mobile URL: https://www.reddit.com/r/uBlockOrigin/wiki/solutions/#wiki_facebook

**Comment by mrinc** [comment]
@fabiogrum What is the url for facebook mobile?  
I can create a version for you to test on mobile - since I did not build this extension for facebook mobile nor do I use it.

**Comment by fabiogrum** [comment]
> @fabiogrum What is the url for facebook mobile?  
> I can create a version for you to test on mobile - since I did not build this extension for facebook mobile nor do I use it.

@mrinc that would be great, thanks. This is the url: https://m.facebook.com/. You can also find filters in the reddit link that I shared.

**Comment by mrinc** [comment]
Ref: [https://github.com/AsadIslam111/F-B-Hide-Recommendations-and-Reels-Mobile-Device-/commit/a682b25f1a172fb75345c928f41b1e053b8df906](https://github.com/AsadIslam111/F-B-Hide-Recommendations-and-Reels-Mobile-Device-/commit/a682b25f1a172fb75345c928f41b1e053b8df906)  

I pushed a change that allows for m.facebook.com, but I couldn't debug it... nor do I use it on mobile.  
Based on above, might need www.m.facebook.com > but this was not what I was seeing.  

Check the latest release if it works on mobile or not, and we can go from there :) (or push a PR for me)
