### ISSUE TITLE
"Follow" suggestions

### ISSUE THREAD

**Issue by generrosity** [mrinc/F-B-Hide-Recommendations-and-Reels#99]
Thank you for maintaining this plugin - it really is nice to have!

I've noticed a new type of FB pushing pages and adverts and annoyances.

These aren't tagged as "suggestions" but obviously they are suggestions of pages to "follow".

I understand this might be quite agressive setting for some people, but I get plenty of suggestion time while on mobile so I don't feel I am missing out at all on desktop!!

Here is a screenshot with the menu inside too, incase you can classify it as a different type.

![image](https://github.com/mrinc/F-B-Hide-Recommendations-and-Reels/assets/12838061/d81d96cf-87f8-4287-9b9a-6e994197d1fc)

**Comment by mrinc** [comment]
Hey,

That seems like a reel, and is picked up but isn't functioning.... mmmm
![image](https://github.com/mrinc/F-B-Hide-Recommendations-and-Reels/assets/4445914/9bd0e8c4-907d-47fb-bc19-8f94a863356d)

If you see this again, please could you post the html of the overarching div element?  
The div that is literally a list item - usually we'd also have added react-elem or some class to this div as well

**Comment by generrosity** [comment]
I think the "shared reels (all birds)" is unrelated to the new "follow" divs.

I have just replicated this tho - and again its "all birds" that triggers it specifically. It doesn't look to be multiple reels in a row etc.

![image](https://github.com/mrinc/F-B-Hide-Recommendations-and-Reels/assets/12838061/9c2f609e-ba11-414e-a30f-3dfb5fce4faf)
![image](https://github.com/mrinc/F-B-Hide-Recommendations-and-Reels/assets/12838061/9f6d4db3-8c06-4b9e-b749-a421eee60992)

HTML of the parent element is thus:
`<div class="x1lliihq redact-elem redact-elemid-8dbc1e36-0c54-43d0-bdb0-bf5256e12f2d can-show redact-elem-reels">`

For the full HTML, see https://justpaste.it/20vu4


If you do have time to check out the 'follow' suggestion a bit more, I can only hope that you can detect the link. Or - potentially - that the second and third element exists just there

Here is the HTML for a "follow" example: https://justpaste.it/deeyl
![image](https://github.com/mrinc/F-B-Hide-Recommendations-and-Reels/assets/12838061/5c8ff497-5902-4e22-9981-db1e0cd6e206)

**Comment by generrosity** [comment]
^ accidental button press, sorry for any extra emails.

For note, AllBirds is a brand I have purchased from but not interacted in Facebook 🤷‍♂️

Obviously if I can help any let me know.

**Comment by mrinc** [comment]
Thanks for the work.   
Seems there is an elem being hidden which is the main cause for this ... mmmmmm  

Question, by any chance, are you using uBlock Origin?
